# .cnb.yml

.pull_code: &pull_code
  - name: sync from github
    # 导入秘钥.
    imports: 
        - https://cnb.cool/serverless-coding/accesskey/-/blob/main/env.yml
    stages:
      - name: sync from github
        image: tencentcom/git-sync
        settings:
          target_url: https://github.com/yiGmMk/TrendRadar.git
          auth_type: https
          username: ${GIT_USERNAME}
          password: ${GIT_ACCESS_TOKEN}
          sync_mode: rebase

main:
  "crontab: 0 1 * * *": # 每天1点执行
    # 简化配置,引用重复的配置 https://docs.cnb.cool/zh/build/simplify-configuration.html
    - <<: *pull_code
  web_trigger_pull_github:
    - <<: *pull_code